# backend/app/services/audio/export.py
"""Export an Audio Overview transcript to PDF or Markdown.

Decision (Patch 010): PDF + Markdown only. PDF covers "send to anyone";
Markdown is the portable, paste-anywhere format the core audience lives in
(Obsidian / Notion / docs). PPTX/DOCX are intentionally out of scope here and
can land later with the enterprise track.

Both exports are citation-backed: every line that carries a `cite` renders the
source reference, and a Sources section lists them at the end.
ASCII punctuation only, so the Markdown passes the T10 lint.
"""
from __future__ import annotations
import io
from typing import List, Optional


def to_markdown(title: str, lines: List[dict],
                sources: Optional[List[dict]] = None) -> str:
    out = [f"# {title}", "", "_Audio Overview transcript, generated by AtlasLM._", ""]
    for ln in lines:
        cite = f" [{ln['cite']}]" if ln.get("cite") else ""
        out.append(f"**{ln['name']}:** {ln['text']}{cite}")
        out.append("")
    if sources:
        out.append("## Sources")
        out.append("")
        for i, s in enumerate(sources, 1):
            label = s.get("source_label") or s.get("name") or "Source"
            url = s.get("external_url") or ""
            out.append(f"{i}. {label}" + (f" - {url}" if url else ""))
    return "\n".join(out).rstrip() + "\n"


def to_pdf(title: str, lines: List[dict],
           sources: Optional[List[dict]] = None) -> bytes:
    """Render a simple, clean transcript PDF. Uses reportlab if present;
    otherwise emits a minimal valid PDF so the endpoint never hard-fails."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer)
    except Exception:  # noqa: BLE001
        return _fallback_pdf(title)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter,
                            topMargin=0.9 * inch, bottomMargin=0.9 * inch)
    ss = getSampleStyleSheet()
    h = ParagraphStyle("Title2", parent=ss["Title"], textColor=HexColor("#0A0A0F"))
    sub = ParagraphStyle("Sub", parent=ss["Normal"], textColor=HexColor("#8A8A99"),
                         fontSize=9, spaceAfter=14)
    nameA = ParagraphStyle("NameA", parent=ss["Normal"], textColor=HexColor("#EC4899"),
                           fontName="Helvetica-Bold", fontSize=10)
    body = ParagraphStyle("Body", parent=ss["Normal"], fontSize=11, leading=16,
                          spaceAfter=10)
    flow = [Paragraph(title, h),
            Paragraph("Audio Overview transcript, generated by AtlasLM.", sub)]
    for ln in lines:
        cite = f' <font color="#FF5A1F">[{ln["cite"]}]</font>' if ln.get("cite") else ""
        flow.append(Paragraph(f'{ln["name"]}', nameA))
        flow.append(Paragraph(f'{ln["text"]}{cite}', body))
    if sources:
        flow.append(Spacer(1, 14))
        flow.append(Paragraph("Sources", nameA))
        for i, s in enumerate(sources, 1):
            label = s.get("source_label") or s.get("name") or "Source"
            url = s.get("external_url") or ""
            flow.append(Paragraph(f"{i}. {label} {url}".strip(), body))
    doc.build(flow)
    return buf.getvalue()


def _fallback_pdf(title: str) -> bytes:
    txt = f"AtlasLM Audio Overview: {title}"
    return (
        b"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
        b"/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>endobj\n"
        b"4 0 obj<</Length 60>>stream\nBT /F1 14 Tf 72 720 Td ("
        + txt.encode("latin-1", "replace")
        + b") Tj ET\nendstream endobj\n"
        b"5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n"
        b"trailer<</Root 1 0 R>>\n%%EOF"
    )
